language: node_js
sudo: false

node_js:
  - "8"

services:
  - redis-server
  - elasticsearch

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - xmlstarlet
      - g++-4.8
      - libpoppler-cpp-dev
      - poppler-utils

install:
  - npm install
  - npm run bootstrap-unix

notifications:
  email: false
